version: '3'
services:
    db:
        image: 'postgres:latest'
        restart: unless-stopped
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - ./db-data:/var/lib/postgresql/data/
        expose:
            - '5000'
        ports:
        - 5000:5000

    worker:
        image: 'ptrxyz/chemotion:latest'
        command: ["start-worker"]
        depends_on:
            - 'db'
        volumes:
            - ./config:/config:ro
            - ./shared:/shared

    eln:
        image: 'ptrxyz/chemotion:latest'
        command: ["start-eln"]
        depends_on:
            - 'db'
        expose:
            - '4000'
        ports:
            - 4000:4000
        volumes:
            - ./config:/config:ro
            - ./shared:/shared
    cadvisor:
        image: google/cadvisor:latest
        container_name: monitoring_cadvisor
        restart: unless-stopped
        depends_on:
            - 'db'
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
        expose:
            - '8080'
        ports: 
            - 8080:8080

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
        - 9090:9090
        command:
        - --config.file=/etc/prometheus/prometheus.yml
        volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
        depends_on:
        - cadvisor
        
    grafana:
        image: grafana/grafana:7.3.6
        container_name: monitoring_grafana
        expose:
            - '3000'
        ports:
        - 3000:3000

    node-exporter:
        image: prom/node-exporter
        container_name: node-exporter
        ports:
            - 9100:9100